kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /data/mpv/
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /data/mpv/
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /data/mpv/
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
#  selector:
#    matchLabels:
#      name: mpv1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---

