kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
  #selector: # unneeded, but good for practice and reference
  #  matchLabels:
  #    name: pv1
