kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/pv1/
  persistentVolumeReclaimPolicy: Retain
