apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo
          imagePullPolicy: IfNotPresent
          #livenessProbe:
          #  exec:
          #    command:
          #      - LAST_LINE=$(echo exit | mongo | tail -n1); if [ "$LAST_LINE" != "bye" ]; then echo $(echo exit | mongo); exit 1; else echo Healthy; fi;
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: claim-1
