kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume-3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 128Mi
  hostPath:
    path: /data/mpv/
  persistentVolumeReclaimPolicy: Retain
