apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  selector:
    app: front-end
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: front-end:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
