apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  selector:
    app: back-end
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back-end
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
      - name: back-end
        image: back-end
        ports:
        - containerPort: 3000
        imagePullPolicy: Never

