apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo
          imagePullPolicy: IfNotPresent
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: claim1
