apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back-end
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: back-end
      annotations:
        # KUBERNETES CAN'T FIND IMAGE!
        #pod.beta.kubernetes.io/init-containers: '[
        #  {
        #    "name": "populate-pets",
        #    "image": "populate-pets:latest"
        #  }
        #]'
    spec:
      containers:
      - name: back-end
        image: back-end
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /pet/Bob
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 1
