kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
#  selector:
#    matchLabels:
#      name: mpv1
